//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faaliyet
    {
        public byte faaliyet_id { get; set; }
        public Nullable<byte> makine_id { get; set; }
        public Nullable<byte> tekniker_id { get; set; }
        public Nullable<byte> operator_id { get; set; }
        public Nullable<byte> durum_id { get; set; }
        public Nullable<byte> ariza_id { get; set; }
        public string calisma_sure { get; set; }
    
        public virtual Ariza Ariza { get; set; }
        public virtual MakineDurum MakineDurum { get; set; }
        public virtual Makineler Makineler { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual Tekniker Tekniker { get; set; }
    }
}
