//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FabrikaEntities : DbContext
    {
        public FabrikaEntities()
            : base("name=FabrikaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ariza> Ariza { get; set; }
        public virtual DbSet<Faaliyet> Faaliyet { get; set; }
        public virtual DbSet<Lastik> Lastik { get; set; }
        public virtual DbSet<MakineDurum> MakineDurum { get; set; }
        public virtual DbSet<Makineler> Makineler { get; set; }
        public virtual DbSet<Operator> Operator { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tekniker> Tekniker { get; set; }
        public virtual DbSet<Uretim> Uretim { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
    }
}
