//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makineler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makineler()
        {
            this.Faaliyet = new HashSet<Faaliyet>();
        }
    
        public byte makine_id { get; set; }
        public string makine_adi { get; set; }
        public string makine_turu { get; set; }
        public Nullable<int> uretim_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faaliyet> Faaliyet { get; set; }
        public virtual Uretim Uretim { get; set; }
    }
}
